export const PENDING_STATES = ['PACKAGE_RECEIVED', 'IN_TRANSIT', 'OUT_FOR_DELIVERY'];

export const COMPLETED_STATES = ['DELIVERED'];
export const CANCELLED_STATES = ['CANCELLED', 'DELIVERED_TO_SENDER'];

export const PENDING = ['PACKAGE_RECEIVED','IN_TRANSIT'];
export const DELIVERING = ['OUT_FOR_DELIVERY'];
